#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#app_lucky_number:
#  path: /hello/{name?Guest}
#  controller: App\Controller\HelloController::hello
#  methods: GET|HEAD


clients_list:
  path: /
  controller: App\Controller\ClientsController::index

#clients_sort:
#  path: /
#  controller: App\Controller\ClientsController::sort


clients_form_add:
  path: /clients/add
  controller: App\Controller\ClientsController::createAndUpdate

clients_form_edit:
  path: /clients/edit/{id<\d+>}
  controller: App\Controller\ClientsController::createAndUpdate

clients_form_delete:
  path: /clients/delete/{id<\d+>}
  controller: App\Controller\ClientsController::delete
