#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#app_lucky_number:
#  path: /hello/{name?Guest}
#  controller: App\Controller\HelloController::hello
#  methods: GET|HEAD

_liip_imagine:
  resource: "@LiipImagineBundle/Resources/config/routing.yaml"

email:
  path: /email
  controller: App\Controller\MailController::sendEmail

register:
  path: /register
  controller: App\Controller\RegistrationController::index

login:
  path: /
  controller: App\Controller\LoginController::index

verify_email:
  path: /verify
  controller: App\Controller\RegistrationController::verifyUserEmail

app_logout:
  path: /logout

clients_list:
  path: /clients
  controller: App\Controller\ClientsController::index

clients_form_add:
  path: /clients/add
  controller: App\Controller\ClientsController::createAndUpdate

clients_form_edit:
  path: /clients/edit/{id<\d+>}
  controller: App\Controller\ClientsController::createAndUpdate

clients_form_delete:
  path: /clients/delete/{id<\d+>}
  controller: App\Controller\ClientsController::delete
